[CmdletBinding()] param([string]$Artifact='',[string]$OutDir='',[string]$Emcc='',[switch]$VerifyOnly,[switch]$PreflightOnly,[switch]$AllowMissing,[switch]$ControllerBuild,[switch]$Clean,[switch]$Force,[switch]$Status)
$ErrorActionPreference='Stop';$Root=(Resolve-Path (Join-Path $PSScriptRoot '../..')).Path;$Cutover=Join-Path $Root 'tools/turbojs_wasm_cutover.py';$Lifecycle=Join-Path $Root 'tools/turbojs_runtime_lifecycle.py';if(!$OutDir){$OutDir=Join-Path $Root 'build/turbojs-wasm'};$OutDir=[System.IO.Path]::GetFullPath($OutDir);if(($OutDir -split '[\\/]' | Where-Object { $_ -eq 'turbojs-wasm' }).Count -gt 2){throw "refusing recursively nested TurboJS/WASM output path: $OutDir"}
function Invoke-VenomExternal{param([string]$Program,[string[]]$Arguments);& $Program @Arguments;$code=$LASTEXITCODE;if($code-ne 0){throw "external command failed with exit code ${code}: $Program"}}
function New-LifecycleArguments{param([string]$Command);@($Command,'--repo-root',$Root,'--out-dir',$OutDir)}
if($Status){& python $Lifecycle status --repo-root $Root --out-dir $OutDir;exit $LASTEXITCODE};if($VerifyOnly){& python $Cutover --repo-root $Root --verify-embedded --require-real;exit $LASTEXITCODE};if($Artifact){& python $Cutover --repo-root $Root --artifact (Resolve-Path $Artifact).Path --require-real;exit $LASTEXITCODE}
if($PreflightOnly){New-Item -ItemType Directory -Force $OutDir|Out-Null;& python (Join-Path $Root 'tools/turbojs_wasm_preflight.py') --repo-root $Root --manifest (Join-Path $OutDir 'turbojs-wasm-preflight.txt') --json (Join-Path $OutDir 'turbojs-wasm-preflight.json') --allow-missing-emcc;exit $LASTEXITCODE}
if(!$ControllerBuild){$a=@('--repo-root',$Root,'--out-dir',$OutDir);if($Emcc){$a+=@('--emcc',$Emcc)};if($Clean){$a+='--clean'};if($Force){$a+='--force'};& python (Join-Path $Root 'tools/build_emscripten.py') @a;exit $LASTEXITCODE}
if($Clean-and(Test-Path $OutDir)){Remove-Item -Recurse -Force $OutDir};New-Item -ItemType Directory -Force $OutDir|Out-Null;$resolvedEmccPath=$Emcc;if(!$resolvedEmccPath){$resolvedEmccPath=(& python $Lifecycle resolve-emcc --repo-root $Root --format path).Trim()};$env:EMCC=$resolvedEmccPath;$E=Join-Path $OutDir 'turbojs-runtime.emcc-exports.json';Invoke-VenomExternal python @((Join-Path $Root 'tools/turbojs_release_abi.py'),$E);$X=((& python -c "import json,sys;print(json.dumps(json.load(open(sys.argv[1],encoding='utf-8')),separators=(',',':')))" $E) -join '').Trim();if($LASTEXITCODE-ne 0){throw "failed to compact TurboJS export list"};$W=Join-Path $OutDir 'turbojs-runtime.wasm'
# Browser/worker WASM uses TurboJS core only; turbojs-libc.c contains POSIX process/signal helpers.
$args=@((Join-Path $Root 'src/runtime/turbojs_runtime_scaffold.c'),(Join-Path $Root 'third_party/turbojs/turbojs.c'),(Join-Path $Root 'third_party/turbojs/libregexp.c'),(Join-Path $Root 'third_party/turbojs/libunicode.c'),(Join-Path $Root 'third_party/turbojs/dtoa.c'),('-I'+(Join-Path $Root 'third_party/turbojs')),'-DCONFIG_VERSION="2026-06-04"','-DCONFIG_BIGNUM','-DVENOM_ENABLE_UPSTREAM_TJS_WASM=1','-DVENOM_TJS_MINIMAL_EXPORTS=1','-O3','-flto','-DNDEBUG','-g0',('-ffile-prefix-map='+$Root+'=.'),('-fdebug-prefix-map='+$Root+'=.'),('-fmacro-prefix-map='+$Root+'=.'),'-sSTANDALONE_WASM=1','-sWASM=1','-sFILESYSTEM=0','-sENVIRONMENT=web,worker','-sALLOW_MEMORY_GROWTH=1','-sINITIAL_MEMORY=16777216','-sMAXIMUM_MEMORY=268435456','-sSTACK_SIZE=4194304','-sMALLOC=emmalloc','-sERROR_ON_UNDEFINED_SYMBOLS=0','-sASSERTIONS=0','-sSAFE_HEAP=0','-sSTACK_OVERFLOW_CHECK=0',('-sEXPORTED_FUNCTIONS='+$X),'--no-entry','-o',$W);try{$emccProgram=$resolvedEmccPath;$emccArguments=$args;if([System.IO.Path]::GetExtension($resolvedEmccPath)-match '^\.(bat|cmd)$'){$emccPy=Join-Path ([System.IO.Path]::GetDirectoryName($resolvedEmccPath)) 'emcc.py';if(!(Test-Path $emccPy)){throw "unable to locate emcc.py next to $resolvedEmccPath"};$emccProgram=if($env:EMSDK_PYTHON){$env:EMSDK_PYTHON}else{(Get-Command python -ErrorAction Stop).Source};$emccArguments=@($emccPy)+$args};Invoke-VenomExternal $emccProgram $emccArguments}catch{throw "emcc failed with exit code ${LASTEXITCODE}: $_"}
$O=(& python $Lifecycle resolve-wasm-opt --repo-root $Root --format path 2>$null);if($LASTEXITCODE-eq 0-and $O){$wasmOptHelp=((& $O --help 2>&1) -join "`n");$wasmOptArgs=@($W,'-O3');foreach($flag in @('--strip-debug','--strip-dwarf','--strip-producers','--detect-features','--enable-bulk-memory-opt','--enable-nontrapping-float-to-int')){if($wasmOptHelp.Contains($flag)){$wasmOptArgs+=$flag}};$wasmOptArgs+=@('-o',"$W.opt");Invoke-VenomExternal $O $wasmOptArgs;Move-Item -Force "$W.opt" $W};Invoke-VenomExternal python @((Join-Path $Root 'tools/check_wasm_release_strings.py'),$W);Invoke-VenomExternal python @($Cutover,'--repo-root',$Root,'--out-dir',$OutDir,'--emcc',$resolvedEmccPath,'--artifact',$W,'--require-real');Invoke-VenomExternal python @($Lifecycle,'write-state','--repo-root',$Root,'--out-dir',$OutDir,'--emcc',$resolvedEmccPath)
