#include "venom/base/error.hpp"
#include "venom/pipeline/js.hpp"
#include "venom/internal/pipeline/js_bundle_encoding.hpp"
#include "venom/internal/pipeline/build_support.hpp"
#include "venom/internal/pipeline/function_dependencies.hpp"
#include "venom/internal/pipeline/js_discovery.hpp"
#include "venom/frontends/javascript/frontend.hpp"
#include "venom/internal/pipeline/js_planning.hpp"
#include "venom/internal/pipeline/js_rewriting.hpp"
#include "venom/internal/pipeline/native_js_hardener.hpp"
#include "venom/generated/runtime/wasm_runtime_blob.hpp"
#include "venom/generated/runtime/quickjs_runtime_wasm_blob.hpp"
#include "venom/quickjs/bytecode.hpp"
#include "venom/package/hash.hpp"

#include <algorithm>
#include <array>
#include <cctype>
#include <cstdint>
#include <iomanip>
#include <functional>
#include <tuple>
#include <regex>
#include <sstream>
#include <stdexcept>
#include <string_view>
#include <unordered_map>
#include <unordered_set>


namespace venom::compiler {


namespace {

std::string make_js_diagnostics(const std::vector<JsChunk>& chunks) {
  std::ostringstream out;
  out << "VJSD0006\n";
  out << "version\t1\n";
  out << "count\t" << chunks.size() << "\n";
  out << "order\troute\tkind\tflags\tsource\tbytes\n";
  for (const auto& chunk : chunks) {
    out << chunk.order << '\t'
        << chunk.route << '\t'
        << chunk.kind << '\t'
        << js_flags_summary(chunk.flags) << '\t'
        << chunk.source << '\t'
        << chunk.code.size() << '\n';
  }
  return out.str();
}

std::string json_escape_plan(const std::string& value) {
  std::ostringstream out;
  for (const char raw_c : value) {
    const auto c = static_cast<unsigned char>(raw_c);
    switch (c) {
      case '\\': out << "\\\\"; break;
      case '"': out << "\\\""; break;
      case '\n': out << '\n'; break;
      case '\r': out << "\\r"; break;
      case '\t': out << "\\t"; break;
      default:
        if (c < 0x20u) out << "\\u" << std::hex << std::setw(4) << std::setfill('0') << static_cast<unsigned int>(c) << std::dec;
        else out << static_cast<char>(c);
    }
  }
  return out.str();
}
std::string make_protected_client_javascript(
    const std::vector<std::pair<std::string, std::string>>& protected_exports) {
  std::ostringstream out;
  out << "// Generated by Venom. Do not edit.\n"
      << "import { callProtected } from '@venom-js/runtime';\n";
  for (const auto& entry : protected_exports) {
    out << "export function " << entry.first
        << "(input, options) { return callProtected(\"" << json_escape_plan(entry.first)
        << "\", input, options); }\n";
  }
  return out.str();
}

std::string make_protected_client_typescript(const std::string& declarations) {
  if (declarations.empty()) return {};
  std::istringstream input(declarations);
  std::ostringstream out;
  out << "// Generated by Venom. Do not edit.\n"
      << "import type { VenomCallOptions } from '@venom-js/runtime';\n";
  std::string line;
  while (std::getline(input, line)) {
    if (line.find("// Generated by Venom") == 0) continue;
    if (line.find("export interface VenomCallOptions") == 0) continue;
    if (!line.empty()) out << line << '\n';
  }
  return out.str();
}


std::string make_protection_intent_ledger_json(
    const std::vector<detail::BridgeRewriteRecord>& records,
    const std::vector<JsChunk>& chunks,
    bool registry_present) {
  std::ostringstream out;
  out << "{\n  \"schema_version\": 1,\n  \"registry_present\": "
      << (registry_present ? "true" : "false") << ",\n  \"intents\": [\n";
  for (std::size_t i = 0; i < records.size(); ++i) {
    const auto& record = records[i];
    out << "    {\"intent_id\":\"" << json_escape_plan(record.candidate)
        << "\",\"source\":\"" << json_escape_plan(record.source)
        << "\",\"symbol\":\"" << json_escape_plan(record.function)
        << "\",\"requested_runtime\":\"protected\",\"terminal_status\":\""
        << (record.status == "extracted" ? "extracted-protected-function" : json_escape_plan(record.status))
        << "\",\"protected_record_id\":";
    if (record.status == "extracted") out << "\"" << json_escape_plan(record.candidate) << "\"";
    else out << "null";
    out << ",\"reason\":\"" << json_escape_plan(record.reason) << "\"}";
    if (i + 1 != records.size()) out << ',';
    out << '\n';
  }
  std::size_t emitted = records.size();
  for (const auto& chunk : chunks) {
    if ((chunk.flags & JsChunkBrowser) != 0u) continue;
    if (emitted++ != 0u) out << ",\n";
    const auto id = "whole-file-" + std::to_string(chunk.order) + "-" + std::to_string(js_envelope_seed("intent", chunk));
    out << "    {\"intent_id\":\"" << id
        << "\",\"source\":\"" << json_escape_plan(chunk.source)
        << "\",\"symbol\":null,\"requested_runtime\":\"protected\",\"terminal_status\":\"compiled-protected-whole-file\",\"protected_record_id\":\""
        << id << "\",\"reason\":\"protected script chunk compiled to QuickJS bytecode\"}";
  }
  if (emitted != 0u) out << '\n';
  out << "  ]\n}\n";
  return out.str();
}

void enforce_protection_intent_closure(const std::vector<detail::BridgeRewriteRecord>& records,
                                       bool registry_present) {
  std::unordered_set<std::string> ids;
  std::size_t resolved = 0;
  for (const auto& record : records) {
    if (record.candidate.empty())
      raise_error("VENOM-E5000", "VNM-PROT-1002: protected intent has no opaque candidate id");
    if (!ids.insert(record.candidate).second)
      raise_error("VENOM-E5000", "VNM-PROT-1003: duplicate protected intent id: " + record.candidate);
    if (record.status == "extracted") ++resolved;
  }
  if (resolved != records.size()) {
    const auto unresolved = std::find_if(records.begin(), records.end(), [](const auto& record) {
      return record.status != "extracted";
    });
    std::string detail;
    if (unresolved != records.end()) {
      detail = ": " + unresolved->source + "::" + unresolved->function + ": " + unresolved->reason;
    }
    raise_error("VENOM-E5000", "VNM-PROT-1004: unresolved protected intents remain after rewrite" + detail);
  }
  if (resolved != 0 && !registry_present)
    raise_error("VENOM-E5000", "VNM-PROT-1005: protected intents resolved without a QuickJS registry record");
}

std::string make_execution_plan_text(const std::vector<JsChunk>& chunks) {
  std::ostringstream out;
  out << "VENOM_EXECUTION_PLAN_V1\n";
  out << "order\troute\texecution\tconfidence\tsource\treason\n";
  for (const auto& chunk : chunks) {
    out << chunk.order << '\t' << chunk.route << '\t'
        << (((chunk.flags & JsChunkBrowser) != 0u) ? "browser" : "protected") << '\t'
        << chunk.execution_confidence << '\t' << chunk.source << '\t' << chunk.execution_reason << '\n';
  }
  return out.str();
}

std::string make_execution_plan_json(const std::vector<JsChunk>& chunks) {
  std::ostringstream out;
  out << "{\n  \"schema_version\": 1,\n  \"scripts\": [\n";
  for (std::size_t i = 0; i < chunks.size(); ++i) {
    const auto& chunk = chunks[i];
    out << "    {\"order\":" << chunk.order
        << ",\"route\":\"" << json_escape_plan(chunk.route)
        << "\",\"source\":\"" << json_escape_plan(chunk.source)
        << "\",\"execution\":\"" << (((chunk.flags & JsChunkBrowser) != 0u) ? "browser" : "protected")
        << "\",\"confidence\":" << chunk.execution_confidence
        << ",\"reason\":\"" << json_escape_plan(chunk.execution_reason)
        << "\",\"flags\":\"" << json_escape_plan(js_flags_summary(chunk.flags)) << "\"}";
    if (i + 1 != chunks.size()) out << ',';
    out << '\n';
  }
  out << "  ]\n}\n";
  return out.str();
}

} // namespace

std::string js_flags_summary(std::uint32_t flags) {
  std::vector<std::string> names;
  if ((flags & JsChunkInline) != 0) names.push_back("inline");
  if ((flags & JsChunkModule) != 0) names.push_back("module");
  if ((flags & JsChunkDefer) != 0) names.push_back("defer");
  if ((flags & JsChunkAsync) != 0) names.push_back("async");
  if ((flags & JsChunkExternalFile) != 0) names.push_back("external-file");
  if ((flags & JsChunkRemoteUrl) != 0) names.push_back("remote-url");
  if ((flags & JsChunkBytecodeEncoded) != 0) names.push_back("bytecode");
  if ((flags & JsChunkVendoredRemote) != 0) names.push_back("vendored-remote");
  if ((flags & JsChunkDependency) != 0) names.push_back("dependency");
  if ((flags & JsChunkDynamicImport) != 0) names.push_back("dynamic-import");
  if ((flags & JsChunkModulePreload) != 0) names.push_back("modulepreload");
  if ((flags & JsChunkBrowser) != 0) names.push_back("browser");
  if ((flags & JsChunkProtectedModule) != 0) names.push_back("protected-module");
  if (names.empty()) return "none";
  std::ostringstream out;
  for (std::size_t i = 0; i < names.size(); ++i) {
    if (i != 0) out << ',';
    out << names[i];
  }
  return out.str();
}

JsBridge compile_js_bridge(const SiteGraph& graph, const RemoteVendorOptions& remote_options, bool development) {
  JsBridge bridge;
  bridge.chunks = detail::collect_script_chunks(graph, remote_options, bridge.remote_vendors, bridge.module_edges);
  const auto initial_function_runtime_records = detail::apply_function_runtime_planning(bridge.chunks);
  detail::close_classic_browser_runtimes(bridge.chunks);
  const auto module_rewrite_result = detail::apply_protected_module_rewrites(bridge.chunks, remote_options.bridge_id_salt, development);
  if (!module_rewrite_result.lowered_browser_imports.empty()) {
    bridge.module_edges.erase(std::remove_if(bridge.module_edges.begin(), bridge.module_edges.end(), [&](const auto& edge) {
      const auto referrer = graph::normalize_module_path(edge.referrer);
      return std::any_of(module_rewrite_result.lowered_browser_imports.begin(), module_rewrite_result.lowered_browser_imports.end(), [&](const auto& lowered) {
        return graph::normalize_module_path(lowered.first) == referrer && lowered.second == edge.specifier;
      });
    }), bridge.module_edges.end());
  }
  const auto function_records = initial_function_runtime_records;
  const auto extraction_records = detail::analyze_function_extraction(bridge.chunks, function_records);
  auto rewrite_result = detail::apply_bridge_rewrites(bridge.chunks, extraction_records, remote_options.bridge_id_salt);
  if (!module_rewrite_result.registry_source.empty()) {
    if (rewrite_result.registry_source.empty()) rewrite_result.registry_source = module_rewrite_result.registry_source;
    else rewrite_result.registry_source += "\n" + module_rewrite_result.registry_source;
    rewrite_result.registry_chunks.insert(rewrite_result.registry_chunks.begin(),
        module_rewrite_result.registry_chunks.begin(), module_rewrite_result.registry_chunks.end());
    rewrite_result.records.insert(rewrite_result.records.begin(), module_rewrite_result.records.begin(), module_rewrite_result.records.end());
  }
  if (!module_rewrite_result.typescript.empty() || !rewrite_result.typescript.empty()) {
    bridge.protected_api_typescript =
        "// Generated by Venom. Do not edit.\n"
        "export interface VenomCallOptions { timeout?: number; signal?: AbortSignal; }\n";
    bridge.protected_api_typescript += module_rewrite_result.typescript;
    bridge.protected_api_typescript += rewrite_result.typescript;
  }
  bridge.diagnostics = make_js_diagnostics(bridge.chunks);
  for (const auto& record : rewrite_result.records) {
    if (record.status == "extracted") continue;
    const std::string diagnostic =
        "VNM-PROT-1001: protected item was not lowered into the protected runtime: " +
        record.source + "::" + record.function + " (status=" + record.status +
        ", reason=" + record.reason + ")";
    if (!development) raise_error("VENOM-E5000", diagnostic);
    bridge.diagnostics += "\nWARNING: " + diagnostic;
  }
  bridge.execution_plan_text = make_execution_plan_text(bridge.chunks);
  bridge.execution_plan_json = make_execution_plan_json(bridge.chunks);
  bridge.function_plan_text = detail::make_function_plan_text(function_records);
  bridge.function_plan_json = detail::make_function_plan_json(function_records);
  bridge.extraction_plan_text = detail::make_extraction_plan_text(extraction_records);
  bridge.extraction_plan_json = detail::make_extraction_plan_json(extraction_records);
  bridge.runtime_bridge_contract_json = detail::make_runtime_bridge_contract_json(extraction_records);
  bridge.bridge_rewrite_report_json = detail::make_bridge_rewrite_report_json(rewrite_result.records);
  bridge.protected_contracts_json = detail::make_protected_contracts_json(rewrite_result.records);
  for (const auto& record : rewrite_result.records) {
    if (record.status == "extracted") {
      bridge.bridge_candidate_ids.push_back(record.candidate);
      bridge.protected_exports.emplace_back(record.function, record.candidate);
      bridge.protected_export_sources.push_back(record.source);
    }
  }
  if (!bridge.protected_exports.empty()) {
    bridge.protected_api_client_javascript = make_protected_client_javascript(bridge.protected_exports);
    bridge.protected_api_client_typescript = make_protected_client_typescript(bridge.protected_api_typescript);
  }

  {
    std::ostringstream lazy;
    lazy << "{\n  \"schema_version\": 2,\n  \"loading_mode\": \"candidate-chunk-activation\",\n  \"exports\": [\n";
    for (std::size_t i = 0; i < bridge.protected_exports.size(); ++i) {
      if (i) lazy << ",\n";
      std::string chunk_id;
      for (const auto& chunk : rewrite_result.registry_chunks) {
        if (std::find(chunk.candidates.begin(), chunk.candidates.end(), bridge.protected_exports[i].second) != chunk.candidates.end()) {
          chunk_id = chunk.id;
          break;
        }
      }
      lazy << "    {\"name\":\"" << json_escape_plan(bridge.protected_exports[i].first)
           << "\",\"candidate\":\"" << json_escape_plan(bridge.protected_exports[i].second)
           << "\",\"source\":\"" << json_escape_plan(i < bridge.protected_export_sources.size() ? bridge.protected_export_sources[i] : std::string{})
           << "\",\"chunk\":\"" << json_escape_plan(chunk_id)
           << "\",\"activation\":\"lazy\"}";
    }
    lazy << "\n  ]\n}\n";
    bridge.lazy_protected_manifest_json = lazy.str();
  }
  if (!rewrite_result.registry_source.empty()) {
    bridge.bridge_registry_bytecode = venom::quickjs::compile_native_quickjs_bytecode(
        development ? rewrite_result.registry_source : build_detail::ast_harden_release_js("protected-registry", rewrite_result.registry_source, remote_options.bridge_id_salt), "v://" + opaque_js_bytecode_label(remote_options.bridge_id_salt, "registry", "root"), false, !development, nullptr);
    const bool native_record = bridge.bridge_registry_bytecode.size() >= 8u &&
        (std::equal(bridge.bridge_registry_bytecode.begin(), bridge.bridge_registry_bytecode.begin() + 8,
                    reinterpret_cast<const unsigned char*>("VQJSBC03")) ||
         std::equal(bridge.bridge_registry_bytecode.begin(), bridge.bridge_registry_bytecode.begin() + 8,
                    reinterpret_cast<const unsigned char*>("VQJSMB04")));
    if (!native_record) {
      raise_error("VENOM-E5000", "protected bridge extraction did not produce a native QuickJS bytecode record");
    }
  }
  for (const auto& source_chunk : rewrite_result.registry_chunks) {
    ProtectedRegistryChunk compiled_chunk;
    compiled_chunk.id = source_chunk.id;
    compiled_chunk.candidates = source_chunk.candidates;
    compiled_chunk.bytecode = venom::quickjs::compile_native_quickjs_bytecode(
        development ? source_chunk.source : build_detail::ast_harden_release_js("protected-registry-chunk", source_chunk.source, remote_options.bridge_id_salt), development ? ("venom://protected-registry/" + source_chunk.id) : ("v://" + opaque_js_bytecode_label(remote_options.bridge_id_salt, "registry-chunk", source_chunk.id)), false, !development, nullptr);
    if (compiled_chunk.bytecode.empty()) raise_error("VENOM-E5000", "protected registry chunk compilation failed: " + source_chunk.id);
    bridge.bridge_registry_chunks.push_back(std::move(compiled_chunk));
  }
  if (!bridge.protected_exports.empty() && bridge.bridge_registry_bytecode.empty()) {
    raise_error("VENOM-E5000", "protected exports exist but the protected QuickJS bridge registry is empty");
  }
  bridge.protected_whole_file_intents = static_cast<std::size_t>(std::count_if(
      bridge.chunks.begin(), bridge.chunks.end(),
      [](const auto& chunk) { return (chunk.flags & JsChunkBrowser) == 0u; }));
  const auto extracted_intents = static_cast<std::size_t>(std::count_if(
      rewrite_result.records.begin(), rewrite_result.records.end(),
      [](const auto& record) { return record.status == "extracted"; }));
  bridge.protected_intents_requested = rewrite_result.records.size() + bridge.protected_whole_file_intents;
  bridge.protected_intents_resolved = extracted_intents + bridge.protected_whole_file_intents;
  bridge.expected_quickjs_records = bridge.protected_whole_file_intents + (!bridge.bridge_registry_bytecode.empty() ? 1u : 0u);
  enforce_protection_intent_closure(rewrite_result.records, !bridge.bridge_registry_bytecode.empty());
  bridge.protection_intent_ledger_json = make_protection_intent_ledger_json(
      rewrite_result.records, bridge.chunks, !bridge.bridge_registry_bytecode.empty());
  bridge.module_graph = graph::build_canonical_module_graph(
      bridge.chunks, bridge.module_edges, remote_options.bridge_id_salt, !development);
  bridge.bundle = encode_js_bundle(bridge.chunks, bridge.module_graph, remote_options.bridge_id_salt, development);

  std::ostringstream preview;
  for (const auto& chunk : bridge.chunks) {
    preview << "\n// route: " << chunk.route << " source: " << chunk.source
            << " flags: " << js_flags_summary(chunk.flags) << "\n";
    preview << chunk.code << "\n";
  }
  bridge.preview = preview.str();
  return bridge;
}



std::vector<unsigned char> encode_protected_bridge_registry(const JsBridge& bridge, const std::string& diversification_salt) {
  if (bridge.bridge_registry_bytecode.empty()) return {};
  JsChunk synthetic;
  synthetic.route = "venom://protected-bridge";
  synthetic.source = "venom://protected-bridge-registry";
  synthetic.order = 0u;
  synthetic.flags = JsChunkBytecodeEncoded;
  synthetic.kind = 0u;
  return wrap_quickjs_record_for_bundle(bridge.bridge_registry_bytecode, diversification_salt, synthetic);
}

std::string js_hash64_literal(std::uint64_t value) {
  std::ostringstream out;
  out << "0x" << std::hex << std::setw(16) << std::setfill('0') << value;
  return out.str();
}

std::string make_loader_js(const std::string& runtime_asset_name, const std::string& package_asset_name, std::uint64_t expected_package_hash, const std::string& expected_package_sha256, bool hardened, const std::string& quickjs_engine_asset_name, const std::string& quickjs_runtime_wasm_asset_name, const std::string& runtime_wasm_asset_name, const std::string& style_asset_name, const std::string& package_binding_token, const std::string& worker_asset_name, const std::string& quickjs_runtime_wasm_sha256, const std::vector<std::pair<std::string, std::string>>& protected_exports,
                           std::uint32_t bridge_invoke_opcode,
                           std::uint32_t bridge_cancel_opcode,
                           std::uint32_t bridge_result_opcode,
                           std::uint32_t bridge_error_opcode) {
  std::ostringstream out;
  out << "import { bootVenom, renderVenomFailure } from './" << runtime_asset_name << "';\n\n";
  out << "const bootOptions = {\n"
      << "  root: document.getElementById('venom-root'),\n"
      << "  packageUrl: new URL('" << package_asset_name << "', import.meta.url).href,\n"
      << "  assetBaseUrl: new URL('" << (hardened ? "../" : "./") << "', import.meta.url).href,\n"
      << "  runtimeUrl: new URL('" << runtime_asset_name << "', import.meta.url).href,\n"
      << "  loaderUrl: import.meta.url,\n"
      << "  expectedPackageHash: '" << js_hash64_literal(expected_package_hash) << "',\n"
      << "  expectedPackageSha256: '" << expected_package_sha256 << "',\n"
      << "  hardened: " << (hardened ? "true" : "false") << ",\n";
  if (!style_asset_name.empty()) out << "  styleUrl: new URL('" << style_asset_name << "', import.meta.url).href,\n";
  if (!runtime_wasm_asset_name.empty()) out << "  runtimeWasmUrl: new URL('" << runtime_wasm_asset_name << "', import.meta.url).href,\n";
  if (!package_binding_token.empty()) out << "  bindingToken: '" << package_binding_token << "',\n";
  if (!quickjs_engine_asset_name.empty()) out << "  quickJsEngineUrl: new URL('" << quickjs_engine_asset_name << "', import.meta.url).href,\n";
  if (!quickjs_runtime_wasm_asset_name.empty()) out << "  quickJsWasmUrl: new URL('" << quickjs_runtime_wasm_asset_name << "', import.meta.url).href,\n";
  if (!quickjs_runtime_wasm_sha256.empty()) out << "  expectedQuickJsWasmSha256: '" << quickjs_runtime_wasm_sha256 << "',\n";
  if (!worker_asset_name.empty()) out << "  workerUrl: new URL('" << worker_asset_name << "', import.meta.url).href,\n";
  out << "};\n";
  out << "const __venomBootStarted=Date.now(),__venomBootTimeline=[],__venomBootAttempt=1;\n"
      << "const __venomFreezeTimeline=()=>Object.freeze(__venomBootTimeline.map((entry)=>Object.freeze({...entry})));\n"
      << "const __venomSetBootStatus=(state,phase,detail)=>{const status=Object.freeze({state,phase,attempt:__venomBootAttempt,startedAt:__venomBootStarted,finishedAt:state==='ready'||state==='error'?Date.now():null,durationMs:Date.now()-__venomBootStarted,timeline:__venomFreezeTimeline(),detail:detail||null});try{Object.defineProperty(globalThis,'__venomBootStatus',{value:status,writable:false,configurable:true});}catch(_){globalThis.__venomBootStatus=status;}return status;};\n"
      << "const __venomRecordBootPhase=(entry)=>{if(!entry||typeof entry.phase!=='string')return;__venomBootTimeline.push({phase:entry.phase,state:String(entry.state||'unknown'),at:Number(entry.at||Date.now()),durationMs:Number(entry.durationMs||0),detail:entry.detail||null});__venomSetBootStatus('initializing',entry.phase,entry.detail||null);try{globalThis.dispatchEvent(new CustomEvent('venom:boot-phase',{detail:Object.freeze({...entry})}));}catch(_){}};\n"
      << "const __venomClassifyBootError=(error)=>{const message=String(error&&error.message||error||'unknown error').toLowerCase();if(message.includes('module dependency not found'))return 'VENOM_BOOT_MODULE_DEPENDENCY';if(message.includes('export surface mismatch'))return 'VENOM_BOOT_WASM_EXPORT_SURFACE';if(message.includes('invalid utf-8'))return 'VENOM_BOOT_INVALID_UTF8';if(message.includes('integrity')||message.includes('hash'))return 'VENOM_BOOT_INTEGRITY';if(message.includes('worker'))return 'VENOM_BOOT_WORKER';if(message.includes('timed out')||message.includes('timeout'))return 'VENOM_BOOT_TIMEOUT';return 'VENOM_BOOT_APPLICATION';};\n"
      << "const __venomSerializeBootError=(error)=>Object.freeze({name:String(error&&error.name||'Error'),message:String(error&&error.message||error||'unknown error'),code:error&&error.code?String(error.code):__venomClassifyBootError(error),recoverable:false,stack:error&&error.stack?String(error.stack):null});\n"
      << "bootOptions.onBootPhase=__venomRecordBootPhase;Object.defineProperty(globalThis,'__venomRetryBoot',{value:()=>{const status=globalThis.__venomBootStatus;if(!status||status.state!=='error')return false;location.reload();return true;},writable:false,configurable:false});\n"
      << "__venomSetBootStatus('initializing','loader',null);\n";
  if (!worker_asset_name.empty()) {
    out << "const __venomInvokeOp=" << bridge_invoke_opcode << ",__venomCancelOp=" << bridge_cancel_opcode << ",__venomResultOp=" << bridge_result_opcode << ",__venomErrorOp=" << bridge_error_opcode << ";\n";
    out << "let __venomReadyResolve,__venomReadyReject; const __venomReadyPromise=new Promise((resolve,reject)=>{__venomReadyResolve=resolve;__venomReadyReject=reject;});\n"
        << "async function prepareWorkerOwnedRuntime() {\n"
        << "  if (typeof Worker !== 'function') throw new Error('protected release requires Web Worker support');\n"
        << "  const worker = new Worker(bootOptions.workerUrl, { type: 'module', name: 'venom-engine' });\n"
        << "  const token = crypto.getRandomValues(new Uint32Array(4));\n"
        << "  const nonce = Array.from(token, (v) => v.toString(16).padStart(8, '0')).join('');\n"
        << "  const bridgeChannel = new MessageChannel();\n"
        << "  const prepared = await new Promise((resolve, reject) => {\n"
        << "    const timer = setTimeout(() => reject(new Error('worker runtime preparation timed out')), 15000);\n"
        << "    worker.onmessage = (event) => { const m = event.data || {}; if (m.nonce !== nonce) return; clearTimeout(timer); if (m.protocol !== 1) return reject(new Error('worker protocol version mismatch')); if (m.type !== 'ready') return reject(new Error(m.message || 'worker runtime preparation failed')); if (m.packageHash !== bootOptions.expectedPackageHash) return reject(new Error('worker package hash attestation mismatch')); if (m.packageSha256 !== bootOptions.expectedPackageSha256) return reject(new Error('worker package SHA-256 attestation mismatch')); if (m.quickJsWasmSha256 !== bootOptions.expectedQuickJsWasmSha256) return reject(new Error('worker QuickJS WASM attestation mismatch')); if (m.quickJsRuntimeReady !== true) return reject(new Error('worker QuickJS WASM readiness attestation missing')); resolve(m); };\n"
        << "    worker.onerror = (event) => { clearTimeout(timer); reject(new Error(event.message || 'worker startup failed')); };\n"
        << "    worker.postMessage({ protocol: 1, type: 'prepare', nonce, packageUrl: bootOptions.packageUrl, quickJsWasmUrl: bootOptions.quickJsWasmUrl, expectedPackageHash: bootOptions.expectedPackageHash, expectedPackageSha256: bootOptions.expectedPackageSha256, expectedQuickJsWasmSha256: bootOptions.expectedQuickJsWasmSha256, maxPackageBytes: 67108864, maxWasmBytes: 33554432 }, [bridgeChannel.port2]);\n"
        << "  });\n"
        << "  bootOptions.packageBytes = prepared.packageBytes;\n"
        << "  if (prepared.quickJsModule) globalThis.__venomWorkerQuickJsModule = prepared.quickJsModule;\n"
        << "  const pendingBridge=new Map(),protectedExports=new Map(),protectedCandidates=new Map(),bridgePort=bridgeChannel.port1;let bridgeSequence=0,bridgeCounter=0,publicRuntimeState='initializing';const bridgeGeneration=Number(prepared.bridgeGeneration)>>>0,bridgeKey=Number(prepared.bridgeKey)>>>0;if(!bridgeGeneration||!bridgeKey)throw new Error('worker binary bridge attestation missing');\n"
        << "  const MAX_PUBLIC_PAYLOAD_BYTES=1048576,MAX_PUBLIC_TIMEOUT_MS=30000,DEFAULT_PUBLIC_TIMEOUT_MS=5000,MAX_PUBLIC_PENDING_CALLS=32,MAX_PUBLIC_JSON_DEPTH=24,MAX_PUBLIC_JSON_NODES=16384,MAX_PUBLIC_BINARY_OBJECTS=64,BINARY_CODEC_VERSION=1,BRIDGE_MAGIC=0x32524256,BRIDGE_HEADER_BYTES=26,BRIDGE_TAG_BYTES=4;const rotateSessionOpcode=(base,lane)=>{let value=((base>>>0)^(bridgeGeneration>>>0)^((bridgeKey<<((lane+3)&15))|(bridgeKey>>>(32-((lane+3)&15)))))>>>0;value=(value+Math.imul(lane+1,0x9e37))&0xffff;return value||((lane+1)*257);};const sessionInvokeOp=rotateSessionOpcode(__venomInvokeOp,0),sessionCancelOp=rotateSessionOpcode(__venomCancelOp,1),sessionResultOp=rotateSessionOpcode(__venomResultOp,2),sessionErrorOp=rotateSessionOpcode(__venomErrorOp,3);if(new Set([sessionInvokeOp,sessionCancelOp,sessionResultOp,sessionErrorOp]).size!==4)throw new Error('worker session opcode collision');const textEncoder=new TextEncoder(),textDecoder=new TextDecoder('utf-8',{fatal:true});\n"
        << "  class VenomBridgeError extends Error{constructor(code,message){super(message);this.name='VenomBridgeError';this.code=code||'BRIDGE_ERROR';}}\n"
        << "  class VenomTimeoutError extends VenomBridgeError{constructor(){super('TIMEOUT','Protected operation timed out');this.name='VenomTimeoutError';}}\n"
        << "  function publicBridgeError(code,message){return new VenomBridgeError(String(code||'BRIDGE_ERROR').toUpperCase().replace(/-/g,'_'),String(message||'Protected operation failed'));}\n"
        << "  function keyedFrameTag(bytes,key){let hash=(2166136261^(key>>>0))>>>0;for(let i=0;i<bytes.length;++i){hash^=bytes[i];hash=Math.imul(hash,16777619)>>>0;}return(hash^((key<<13)|(key>>>19)))>>>0;}\n"
        << "  function binaryTypeName(v){if(v instanceof ArrayBuffer)return 'ArrayBuffer';if(!ArrayBuffer.isView(v)||v instanceof DataView)return '';const n=v.constructor&&v.constructor.name;return ['Uint8Array','Uint8ClampedArray','Int8Array','Uint16Array','Int16Array','Uint32Array','Int32Array','Float32Array','Float64Array'].includes(n)?n:'';}\n"
        << "  function encodePayload(value){const blobs=[];let nodes=0;const visit=(v,d)=>{if(++nodes>MAX_PUBLIC_JSON_NODES||d>MAX_PUBLIC_JSON_DEPTH)throw new RangeError('Protected value exceeds structural limits');const t=binaryTypeName(v);if(t){if(blobs.length>=MAX_PUBLIC_BINARY_OBJECTS)throw new RangeError('Protected value exceeds binary object limit');const b=v instanceof ArrayBuffer?new Uint8Array(v):new Uint8Array(v.buffer,v.byteOffset,v.byteLength),i=blobs.length;blobs.push(b.slice());return{__venomBinary:i,type:t,byteLength:b.byteLength};}if(v===null||typeof v==='string'||typeof v==='boolean')return v;if(typeof v==='number'){if(!Number.isFinite(v))throw new TypeError('Protected value contains a non-finite number');return v;}if(Array.isArray(v))return v.map(x=>visit(x,d+1));if(typeof v==='object'){const p=Object.getPrototypeOf(v);if(p!==Object.prototype&&p!==null)throw new TypeError('Protected value contains unsupported object');const o=Object.create(null);for(const k of Object.keys(v)){if(k==='__proto__'||k==='prototype'||k==='constructor'||k==='__venomBinary')throw new TypeError('Protected value contains forbidden property');o[k]=visit(v[k],d+1);}return o;}throw new TypeError('Protected value contains unsupported type');};const m=textEncoder.encode(JSON.stringify(visit(value,0)));let z=7+m.byteLength;for(const b of blobs)z+=4+b.byteLength;if(z>MAX_PUBLIC_PAYLOAD_BYTES)throw new RangeError('Protected value exceeds the 1 MiB bridge limit');const p=new Uint8Array(z),dv=new DataView(p.buffer);p[0]=BINARY_CODEC_VERSION;dv.setUint32(1,m.byteLength,true);dv.setUint16(5,blobs.length,true);p.set(m,7);let o=7+m.byteLength;for(const b of blobs){dv.setUint32(o,b.byteLength,true);o+=4;p.set(b,o);o+=b.byteLength;b.fill(0);}return p;}\n"
        << "  function decodePayload(p){if(!p.byteLength)return undefined;if(p[0]!==BINARY_CODEC_VERSION||p.byteLength<7)throw new Error('unsupported bridge payload codec');const dv=new DataView(p.buffer,p.byteOffset,p.byteLength),ml=dv.getUint32(1,true),bc=dv.getUint16(5,true);if(bc>MAX_PUBLIC_BINARY_OBJECTS||7+ml>p.byteLength)throw new Error('invalid bridge payload');const meta=JSON.parse(textDecoder.decode(p.subarray(7,7+ml))),blobs=[];let o=7+ml;for(let i=0;i<bc;i++){if(o+4>p.byteLength)throw new Error('invalid bridge blob table');const l=dv.getUint32(o,true);o+=4;if(o+l>p.byteLength)throw new Error('invalid bridge blob length');blobs.push(p.slice(o,o+l));o+=l;}if(o!==p.byteLength)throw new Error('bridge payload trailing bytes');const revive=(v,d=0)=>{if(d>MAX_PUBLIC_JSON_DEPTH)throw new Error('bridge payload exceeds depth limit');if(v&&typeof v==='object'&&!Array.isArray(v)&&Number.isInteger(v.__venomBinary)){const b=blobs[v.__venomBinary];if(!b||b.byteLength!==Number(v.byteLength))throw new Error('invalid bridge binary reference');const ab=b.slice().buffer;if(v.type==='ArrayBuffer')return ab;const C=globalThis[v.type];if(typeof C!=='function'||!['Uint8Array','Uint8ClampedArray','Int8Array','Uint16Array','Int16Array','Uint32Array','Int32Array','Float32Array','Float64Array'].includes(v.type)||ab.byteLength%C.BYTES_PER_ELEMENT)throw new Error('unsupported bridge binary type');return new C(ab);}if(Array.isArray(v))return v.map(x=>revive(x,d+1));if(v&&typeof v==='object')for(const k of Object.keys(v))v[k]=revive(v[k],d+1);return v;};return revive(meta);};\n"
        << "  function encodeFrame(op,counter,capability,requestId,value){const r=textEncoder.encode(String(requestId||'')),p=value===undefined?new Uint8Array(0):encodePayload(value);if(r.byteLength>96||p.byteLength>MAX_PUBLIC_PAYLOAD_BYTES)throw new RangeError('bridge frame exceeds protocol limit');const b=new ArrayBuffer(BRIDGE_HEADER_BYTES+r.byteLength+p.byteLength+BRIDGE_TAG_BYTES),v=new DataView(b),a=new Uint8Array(b);v.setUint32(0,BRIDGE_MAGIC,true);v.setUint16(4,1,true);v.setUint16(6,op>>>0,true);v.setUint32(8,bridgeGeneration,true);v.setUint32(12,counter>>>0,true);v.setUint32(16,capability>>>0,true);v.setUint16(20,r.byteLength,true);v.setUint32(22,p.byteLength,true);a.set(r,BRIDGE_HEADER_BYTES);a.set(p,BRIDGE_HEADER_BYTES+r.byteLength);v.setUint32(b.byteLength-BRIDGE_TAG_BYTES,keyedFrameTag(a.subarray(0,b.byteLength-BRIDGE_TAG_BYTES),bridgeKey),true);p.fill(0);return b;}\n"
        << "  function decodeFrame(b){if(!(b instanceof ArrayBuffer)||b.byteLength<BRIDGE_HEADER_BYTES+BRIDGE_TAG_BYTES)throw new Error('invalid bridge frame');const v=new DataView(b),a=new Uint8Array(b);if(v.getUint32(0,true)!==BRIDGE_MAGIC||v.getUint16(4,true)!==1||v.getUint32(8,true)!==bridgeGeneration)throw new Error('bridge frame attestation mismatch');const rl=v.getUint16(20,true),pl=v.getUint32(22,true);if(BRIDGE_HEADER_BYTES+rl+pl+BRIDGE_TAG_BYTES!==b.byteLength)throw new Error('bridge frame length mismatch');if(v.getUint32(b.byteLength-BRIDGE_TAG_BYTES,true)!==keyedFrameTag(a.subarray(0,b.byteLength-BRIDGE_TAG_BYTES),bridgeKey))throw new Error('bridge frame integrity mismatch');const id=textDecoder.decode(a.subarray(BRIDGE_HEADER_BYTES,BRIDGE_HEADER_BYTES+rl)),ps=BRIDGE_HEADER_BYTES+rl;return{op:v.getUint16(6,true)>>>0,counter:v.getUint32(12,true)>>>0,id,value:decodePayload(a.subarray(ps,ps+pl))};}\n"
        << "  function sendFrame(op,counter,capability,id,value){const frame=encodeFrame(op,counter,capability,id,value);bridgePort.postMessage(frame,[frame]);}\n"
        << "  bridgePort.onmessage=(event)=>{let m;try{m=decodeFrame(event.data);}catch(_){return;}const p=pendingBridge.get(m.id);if(!p||m.counter!==p.counter||(m.op!==sessionResultOp&&m.op!==sessionErrorOp))return;pendingBridge.delete(m.id);clearTimeout(p.timer);if(p.abortCleanup)p.abortCleanup();if(m.op===sessionResultOp)p.resolve(m.value);else p.reject(publicBridgeError(m.value&&m.value.code,m.value&&m.value.message));};bridgePort.start();\n"
        << "  function validatePublicJson(value,label){let nodes=0;const visit=(v,depth)=>{if(++nodes>MAX_PUBLIC_JSON_NODES)throw new RangeError(label+' exceeds the JSON node limit');if(depth>MAX_PUBLIC_JSON_DEPTH)throw new RangeError(label+' exceeds the JSON depth limit');if(binaryTypeName(v)){if(v.byteLength>MAX_PUBLIC_PAYLOAD_BYTES)throw new RangeError(label+' binary value exceeds the bridge limit');return;}if(v===null||typeof v==='string'||typeof v==='boolean')return;if(typeof v==='number'){if(!Number.isFinite(v))throw new TypeError(label+' contains a non-finite number');return;}if(Array.isArray(v)){for(const item of v)visit(item,depth+1);return;}if(typeof v==='object'){const proto=Object.getPrototypeOf(v);if(proto!==Object.prototype&&proto!==null)throw new TypeError(label+' contains a non-plain object');for(const key of Object.keys(v)){if(key==='__proto__'||key==='prototype'||key==='constructor')throw new TypeError(label+' contains a forbidden property');visit(v[key],depth+1);}return;}throw new TypeError(label+' contains an unsupported value');};visit(value,0);}function encodePublicValue(value,label){validatePublicJson(value,label);encodePayload(value);return value;}\n"
        << "  function baseCapabilityForSlot(slot){return((((__venomInvokeOp>>>0)^0x9e3779b9)+((slot+1)>>>0)*0x85ebca6b)>>>0)|1;}function leaseCapabilityForSlot(slot,counter){let value=(baseCapabilityForSlot(slot)^bridgeGeneration^Math.imul(counter>>>0,0x85ebca6b)^bridgeKey)>>>0;value^=value>>>16;value=Math.imul(value,0x7feb352d)>>>0;value^=value>>>15;return(value|1)>>>0;}\n"
        << "  function invokeCandidate(candidateSlot,args,options){options=options||{};if(pendingBridge.size>=MAX_PUBLIC_PENDING_CALLS)return Promise.reject(publicBridgeError('BUSY','Too many protected operations are pending'));let normalized;try{normalized=encodePublicValue(Array.isArray(args)?args:[],'Protected arguments');}catch(error){error.code='INVALID_ARGUMENTS';return Promise.reject(error);}candidateSlot=Number(candidateSlot);if(!Number.isInteger(candidateSlot)||candidateSlot<0)return Promise.reject(publicBridgeError('UNKNOWN_EXPORT','Unknown protected export'));const timeout=Math.max(1,Math.min(MAX_PUBLIC_TIMEOUT_MS,Number(options.timeout)||DEFAULT_PUBLIC_TIMEOUT_MS)),signal=options.signal;if(signal&&signal.aborted)return Promise.reject(new DOMException('The protected operation was aborted','AbortError'));return new Promise((resolve,reject)=>{const requestId='v'+Date.now().toString(36)+(++bridgeSequence).toString(36)+crypto.getRandomValues(new Uint32Array(1))[0].toString(36),counter=++bridgeCounter,capability=leaseCapabilityForSlot(candidateSlot,counter);let settled=false;const finish=(fn,value)=>{if(settled)return;settled=true;pendingBridge.delete(requestId);clearTimeout(timer);if(abortCleanup)abortCleanup();fn(value);};const timer=setTimeout(()=>{sendFrame(sessionCancelOp,++bridgeCounter,0,requestId);finish(reject,new VenomTimeoutError());},timeout);let abortCleanup=null;if(signal){const onAbort=()=>{sendFrame(sessionCancelOp,++bridgeCounter,0,requestId);finish(reject,new DOMException('The protected operation was aborted','AbortError'));};signal.addEventListener('abort',onAbort,{once:true});abortCleanup=()=>signal.removeEventListener('abort',onAbort);}pendingBridge.set(requestId,{resolve:(v)=>finish(resolve,v),reject:(e)=>finish(reject,e),timer,abortCleanup,counter});sendFrame(sessionInvokeOp,counter,capability,requestId,normalized);});}\n"
        << "  globalThis.__venomInvokeProtected=(candidateSlot,args,options)=>invokeCandidate(candidateSlot,args,options);\n"
        << "  globalThis.__venomInvokeProtectedById=(candidate,args,options)=>{const candidateSlot=protectedCandidates.get(String(candidate||''));if(candidateSlot===undefined)return Promise.reject(publicBridgeError('UNKNOWN_EXPORT','Unknown protected export'));return invokeCandidate(candidateSlot,args,options);};\n"
        << "  globalThis.__venomRegisterProtectedExport=(name,candidate,candidateSlot)=>{name=String(name||'');candidate=String(candidate||'');candidateSlot=Number(candidateSlot);if(!/^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name)||!candidate||!Number.isInteger(candidateSlot)||candidateSlot<0)throw new Error('invalid protected export registration');const prior=protectedExports.get(name),priorCandidate=protectedCandidates.get(candidate);if((prior!==undefined&&prior!==candidateSlot)||(priorCandidate!==undefined&&priorCandidate!==candidateSlot))throw new Error('duplicate protected export registration');protectedExports.set(name,candidateSlot);protectedCandidates.set(candidate,candidateSlot);};\n";
    for (std::size_t export_index = 0; export_index < protected_exports.size(); ++export_index) {
      const auto& entry = protected_exports[export_index];
      out << "  globalThis.__venomRegisterProtectedExport(\"" << json_escape_plan(entry.first) << "\",\"" << json_escape_plan(entry.second) << "\"," << export_index << ");\n";
    }
    out        << "  const assertPublicRuntimeActive=()=>{if(publicRuntimeState==='disposed')throw publicBridgeError('RUNTIME_DISPOSED','Venom runtime has been disposed');};\n"
        << "  const callProtected=(name,input,options)=>{try{assertPublicRuntimeActive();}catch(error){return Promise.reject(error);}const candidateSlot=protectedExports.get(String(name||''));if(candidateSlot===undefined)return Promise.reject(publicBridgeError('UNKNOWN_EXPORT','Unknown protected export'));return invokeCandidate(candidateSlot,[input],options);};\n"
        << "  const batchProtected=(calls,options)=>{try{assertPublicRuntimeActive();}catch(error){return Promise.reject(error);}if(!Array.isArray(calls))return Promise.reject(publicBridgeError('INVALID_BATCH','Protected batch must be an array'));if(calls.length===0)return Promise.resolve([]);if(calls.length>MAX_PUBLIC_PENDING_CALLS)return Promise.reject(publicBridgeError('BATCH_LIMIT','Protected batch exceeds the pending-call limit'));const normalized=[];for(let i=0;i<calls.length;i++){const item=calls[i];if(!item||typeof item!=='object'||Array.isArray(item))return Promise.reject(publicBridgeError('INVALID_BATCH','Protected batch item '+i+' must be an object'));const name=String(item.name||'');if(!protectedExports.has(name))return Promise.reject(publicBridgeError('UNKNOWN_EXPORT','Unknown protected export in batch: '+name));normalized.push({name,input:item.input,options:item.options||options});}return Promise.all(normalized.map(item=>callProtected(item.name,item.input,item.options)));};\n"
        << "  const preloadProtected=(names)=>{try{assertPublicRuntimeActive();}catch(error){return Promise.reject(error);}const requested=(Array.isArray(names)?names:[names]).map(String),missing=requested.filter(name=>!protectedExports.has(name));if(missing.length)return Promise.reject(publicBridgeError('UNKNOWN_EXPORT','Unknown protected exports: '+missing.join(', ')));return Promise.resolve(Object.freeze({ready:Object.freeze(requested.slice()),loaded:false}));};\n"
        << "  const runtimeStatus=()=>Object.freeze({state:publicRuntimeState,ready:publicRuntimeState==='ready',disposed:publicRuntimeState==='disposed',pendingCalls:pendingBridge.size,exports:Object.freeze(Array.from(protectedExports.keys()).sort())});\n"
        << "  const disposeProtectedRuntime=(reason)=>{if(publicRuntimeState==='disposed')return runtimeStatus();publicRuntimeState='disposed';const error=publicBridgeError('RUNTIME_DISPOSED',String(reason||'Venom runtime disposed'));for(const [id,pending] of pendingBridge){pendingBridge.delete(id);clearTimeout(pending.timer);if(pending.abortCleanup)pending.abortCleanup();pending.reject(error);}try{bridgePort.close();}catch(_){}try{worker.terminate();}catch(_){}try{const internal=globalThis.__venomRuntime;if(internal&&typeof internal.teardownRoute==='function')internal.teardownRoute(String(reason||'runtime-disposed'));}catch(_){}try{globalThis.dispatchEvent(new CustomEvent('venom:disposed',{detail:runtimeStatus()}));}catch(_){}return runtimeStatus();};\n"
        << "  const venomApi=Object.freeze({apiVersion:1,ready:()=>__venomReadyPromise,call:callProtected,batch:batchProtected,preload:preloadProtected,status:runtimeStatus,dispose:disposeProtectedRuntime,info:()=>Object.freeze({runtimeApiVersion:1,protocol:1,transport:'binary-capability-v3-leased',valueContract:'binary-json-v2',batching:'parallel-v1',maxBatchCalls:MAX_PUBLIC_PENDING_CALLS,maxPayloadBytes:MAX_PUBLIC_PAYLOAD_BYTES,maxTimeoutMs:MAX_PUBLIC_TIMEOUT_MS,maxPendingCalls:MAX_PUBLIC_PENDING_CALLS,maxJsonDepth:MAX_PUBLIC_JSON_DEPTH,maxJsonNodes:MAX_PUBLIC_JSON_NODES,maxBinaryObjects:MAX_PUBLIC_BINARY_OBJECTS,binaryTypes:Object.freeze(['ArrayBuffer','Uint8Array','Uint8ClampedArray','Int8Array','Uint16Array','Int16Array','Uint32Array','Int32Array','Float32Array','Float64Array']),exports:Array.from(protectedExports.keys()).sort()}),exports:new Proxy(Object.create(null),{get:(_,name)=>typeof name==='string'&&protectedExports.has(name)?((input,options)=>venomApi.call(name,input,options)):undefined,has:(_,name)=>typeof name==='string'&&protectedExports.has(name),ownKeys:()=>Array.from(protectedExports.keys()).sort(),getOwnPropertyDescriptor:(_,name)=>typeof name==='string'&&protectedExports.has(name)?{enumerable:true,configurable:true}:undefined,set:()=>false})});\n"
        << "  Object.defineProperty(globalThis,'venom',{value:venomApi,writable:false,configurable:false,enumerable:true});\n"
        << "  publicRuntimeState='ready';__venomReadyResolve(venomApi);try{globalThis.dispatchEvent(new CustomEvent('venom:ready',{detail:venomApi}));}catch(_){}\n"
        << "}\n"
        << "prepareWorkerOwnedRuntime().then(()=>{__venomSetBootStatus('initializing','application',null);return bootVenom(bootOptions);}).then((report)=>{const status=__venomSetBootStatus('ready','complete',report);try{globalThis.dispatchEvent(new CustomEvent('venom:boot-ready',{detail:status}));}catch(_){}return report;}).catch((error) => { __venomReadyReject(error); const status=__venomSetBootStatus('error','application',__venomSerializeBootError(error)); try{globalThis.dispatchEvent(new CustomEvent('venom:error',{detail:error}));globalThis.dispatchEvent(new CustomEvent('venom:boot-error',{detail:status}));}catch(_){} console.error('[venom] boot failed', error); renderVenomFailure(bootOptions.root, error); });\n";
  } else {
    out << "bootVenom(bootOptions).then((report)=>{const status=__venomSetBootStatus('ready','complete',report);try{globalThis.dispatchEvent(new CustomEvent('venom:boot-ready',{detail:status}));}catch(_){}return report;}).catch((error) => { const status=__venomSetBootStatus('error','application',__venomSerializeBootError(error)); try{globalThis.dispatchEvent(new CustomEvent('venom:boot-error',{detail:status}));}catch(_){} console.error('[venom] boot failed', error); renderVenomFailure(bootOptions.root, error); });\n";
  }
  return out.str();
}

std::string bundle_js_preview(const SiteGraph& graph) {
  std::ostringstream out;
  for (const auto& file : graph.files) {
    if (file.extension == ".js" || file.extension == ".mjs") {
      out << "\n// source: " << file.relative << "\n";
      out.write(reinterpret_cast<const char*>(file.bytes.data()), static_cast<std::streamsize>(file.bytes.size()));
      out << "\n";
    }
  }
  return out.str();
}

} // namespace venom::compiler
