[CmdletBinding()] param([string]$Artifact='',[string]$OutDir='',[string]$Emcc='',[switch]$VerifyOnly,[switch]$PreflightOnly,[switch]$AllowMissing,[switch]$ControllerBuild,[switch]$Clean,[switch]$Force,[switch]$Status)
$ErrorActionPreference='Stop';$Root=(Resolve-Path (Join-Path $PSScriptRoot '..')).Path;$Cutover=Join-Path $Root 'tools/quickjs_wasm_cutover.py';$Lifecycle=Join-Path $Root 'tools/quickjs_runtime_lifecycle.py';if(!$OutDir){$OutDir=Join-Path $Root 'build/quickjs-wasm'}
function Invoke-VenomExternal{param([string]$Program,[string[]]$Arguments);& $Program @Arguments;$code=$LASTEXITCODE;if($code-ne 0){throw "external command failed with exit code ${code}: $Program"}}
function New-LifecycleArguments{param([string]$Command);@($Command,'--repo-root',$Root,'--out-dir',$OutDir)}
if($Status){& python $Lifecycle status --repo-root $Root --out-dir $OutDir;exit $LASTEXITCODE};if($VerifyOnly){& python $Cutover --repo-root $Root --verify-embedded --require-real;exit $LASTEXITCODE};if($Artifact){& python $Cutover --repo-root $Root --artifact (Resolve-Path $Artifact).Path --require-real;exit $LASTEXITCODE}
if($PreflightOnly){New-Item -ItemType Directory -Force $OutDir|Out-Null;& python (Join-Path $Root 'tools/quickjs_wasm_preflight.py') --repo-root $Root --manifest (Join-Path $OutDir 'quickjs-wasm-preflight.txt') --json (Join-Path $OutDir 'quickjs-wasm-preflight.json') --allow-missing-emcc;exit $LASTEXITCODE}
if(!$ControllerBuild){$a=@('--repo-root',$Root,'--out-dir',$OutDir);if($Emcc){$a+=@('--emcc',$Emcc)};if($Clean){$a+='--clean'};if($Force){$a+='--force'};& python (Join-Path $Root 'tools/build_emscripten.py') @a;exit $LASTEXITCODE}
if($Clean-and(Test-Path $OutDir)){Remove-Item -Recurse -Force $OutDir};New-Item -ItemType Directory -Force $OutDir|Out-Null;$resolvedEmccPath=$Emcc;if(!$resolvedEmccPath){$resolvedEmccPath=(& python $Lifecycle resolve-emcc --repo-root $Root --format path).Trim()};$env:EMCC=$resolvedEmccPath;$E=Join-Path $OutDir 'quickjs-runtime.emcc-exports.json';Invoke-VenomExternal python @((Join-Path $Root 'tools/quickjs_release_abi.py'),$E);$X=(Get-Content -Raw $E).Trim();$W=Join-Path $OutDir 'quickjs-runtime.wasm'
$args=@((Join-Path $Root 'src/runtime/quickjs_runtime_scaffold.c'),(Join-Path $Root 'third_party/quickjs/quickjs.c'),(Join-Path $Root 'third_party/quickjs/quickjs-libc.c'),(Join-Path $Root 'third_party/quickjs/libregexp.c'),(Join-Path $Root 'third_party/quickjs/libunicode.c'),(Join-Path $Root 'third_party/quickjs/dtoa.c'),('-I'+(Join-Path $Root 'third_party/quickjs')),'-DCONFIG_VERSION="2026-06-04"','-DCONFIG_BIGNUM','-DVENOM_ENABLE_UPSTREAM_QJS_WASM=1','-DVENOM_QJS_MINIMAL_EXPORTS=1','-O3','-flto','-DNDEBUG','-g0',('-ffile-prefix-map='+$Root+'=.'),('-fdebug-prefix-map='+$Root+'=.'),('-fmacro-prefix-map='+$Root+'=.'),'-sSTANDALONE_WASM=1','-sWASM=1','-sFILESYSTEM=0','-sENVIRONMENT=web,worker','-sALLOW_MEMORY_GROWTH=1','-sINITIAL_MEMORY=16777216','-sMAXIMUM_MEMORY=268435456','-sSTACK_SIZE=4194304','-sMALLOC=emmalloc','-sERROR_ON_UNDEFINED_SYMBOLS=0','-sASSERTIONS=0','-sSAFE_HEAP=0','-sSTACK_OVERFLOW_CHECK=0',('-sEXPORTED_FUNCTIONS='+$X),'--no-entry','-o',$W);try{Invoke-VenomExternal $resolvedEmccPath $args}catch{throw "emcc failed with exit code ${LASTEXITCODE}: $_"}
$wasmFeatureFlags=@('--detect-features','--enable-bulk-memory-opt','--enable-nontrapping-float-to-int');$O=(& python $Lifecycle resolve-wasm-opt --repo-root $Root --format path 2>$null);if($LASTEXITCODE-eq 0-and $O){Invoke-VenomExternal $O (@($W,'-O3','--strip-all')+$wasmFeatureFlags+@('-o',"$W.opt"));Move-Item -Force "$W.opt" $W};Invoke-VenomExternal python @((Join-Path $Root 'tools/check_wasm_release_strings.py'),$W);Invoke-VenomExternal python @($Cutover,'--repo-root',$Root,'--out-dir',$OutDir,'--emcc',$resolvedEmccPath,'--artifact',$W,'--require-real');Invoke-VenomExternal python @($Lifecycle,'write-state','--repo-root',$Root,'--out-dir',$OutDir,'--emcc',$resolvedEmccPath)
