#!/usr/bin/env python3
import argparse, json
from pathlib import Path

def render_h(d):
    return f'''// Generated by tools/generate_product_contracts.py. Do not edit.\n#pragma once\n#include <cstdint>\n#include <string_view>\nnamespace venom::contracts {{\ninline constexpr std::uint32_t kSchemaVersion = {d["schema_version"]}u;\ninline constexpr std::uint32_t kPackageFormatVersion = {d["package_format_version"]}u;\ninline constexpr std::uint32_t kPackageRuntimeAbi = {d["package_runtime_abi"]}u;\ninline constexpr std::string_view kRouteVmContract = "{d["route_vm_contract"]}";\ninline constexpr std::string_view kDomCommandContract = "{d["dom_command_contract"]}";\ninline constexpr std::string_view kQuickJsModuleBundleContract = "{d["quickjs_module_bundle_contract"]}";\ninline constexpr std::uint32_t kQuickJsRuntimeAbi = {d["quickjs_runtime_abi"]}u;\ninline constexpr std::uint32_t kHostBridgeAbi = {d["host_bridge_abi"]}u;\ninline constexpr std::uint32_t kConfigurationSchema = {d["configuration_schema"]}u;\ninline constexpr std::uint32_t kLockfileSchema = {d["lockfile_schema"]}u;\n}} // namespace venom::contracts\n'''

def render_py(d):
    return '# Generated by tools/generate_product_contracts.py. Do not edit.\nCONTRACTS = ' + repr(d) + '\n'

def main():
    ap=argparse.ArgumentParser(); ap.add_argument('--repo-root',default='.'); ap.add_argument('--check',action='store_true'); a=ap.parse_args()
    root=Path(a.repo_root).resolve(); d=json.loads((root/'contracts/product-contracts.json').read_text())
    outputs={root/'include/venom/generated/contracts/product_contracts.hpp':render_h(d), root/'tools/product_contracts.py':render_py(d)}
    bad=[]
    for p,text in outputs.items():
        if a.check:
            if not p.exists() or p.read_text()!=text: bad.append(str(p.relative_to(root)))
        else:
            p.parent.mkdir(parents=True,exist_ok=True); p.write_text(text)
    if bad:
        print('stale generated product contracts: '+', '.join(bad)); return 1
    if not a.check: print('[venom] generated product contract bindings')
    return 0
if __name__=='__main__': raise SystemExit(main())
