# Build acceleration controls for contributor and CI builds.

set(VENOM_COMPILER_CACHE "auto" CACHE STRING "Compiler cache: auto, none, ccache, or sccache")
set_property(CACHE VENOM_COMPILER_CACHE PROPERTY STRINGS auto none ccache sccache)
option(VENOM_ENABLE_PCH "Use a precompiled header for the C++ compiler pipeline" ON)
option(VENOM_ENABLE_MSVC_MP "Enable MSVC multi-process compilation (/MP)" ON)
option(VENOM_ENABLE_QUICKJS_IPO "Apply IPO/LTO to the vendored QuickJS static library" OFF)

function(venom_configure_compiler_cache)
  string(TOLOWER "${VENOM_COMPILER_CACHE}" _venom_cache_mode)
  if(_venom_cache_mode STREQUAL "none")
    message(STATUS "Compiler cache disabled")
    return()
  endif()

  set(_venom_cache_candidates)
  if(_venom_cache_mode STREQUAL "auto")
    list(APPEND _venom_cache_candidates sccache ccache)
  elseif(_venom_cache_mode MATCHES "^(sccache|ccache)$")
    list(APPEND _venom_cache_candidates "${_venom_cache_mode}")
  else()
    message(FATAL_ERROR "VENOM_COMPILER_CACHE must be auto, none, ccache, or sccache")
  endif()

  foreach(_candidate IN LISTS _venom_cache_candidates)
    find_program(_venom_cache_program NAMES "${_candidate}")
    if(_venom_cache_program)
      set(CMAKE_C_COMPILER_LAUNCHER "${_venom_cache_program}" CACHE FILEPATH "C compiler launcher" FORCE)
      set(CMAKE_CXX_COMPILER_LAUNCHER "${_venom_cache_program}" CACHE FILEPATH "C++ compiler launcher" FORCE)
      message(STATUS "Compiler cache: ${_candidate} (${_venom_cache_program})")
      return()
    endif()
  endforeach()

  if(NOT _venom_cache_mode STREQUAL "auto")
    message(FATAL_ERROR "Requested compiler cache '${_venom_cache_mode}' was not found")
  endif()
  message(STATUS "Compiler cache: unavailable (continuing without one)")
endfunction()

function(venom_apply_build_acceleration target)
  if(MSVC AND VENOM_ENABLE_MSVC_MP)
    target_compile_options(${target} PRIVATE /MP)
  endif()
endfunction()
